# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autofocus.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Autofocus(object):
    def setupUi(self, Autofocus):
        Autofocus.setObjectName("Autofocus")
        Autofocus.resize(896, 325)
        self.verticalLayout = QtWidgets.QVBoxLayout(Autofocus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.focusGroup = QtWidgets.QGroupBox(Autofocus)
        self.focusGroup.setObjectName("focusGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.focusGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.delaySlider = QtWidgets.QSlider(self.focusGroup)
        self.delaySlider.setMinimumSize(QtCore.QSize(100, 0))
        self.delaySlider.setMaximum(20)
        self.delaySlider.setPageStep(1)
        self.delaySlider.setProperty("value", 3)
        self.delaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.delaySlider.setObjectName("delaySlider")
        self.horizontalLayout_2.addWidget(self.delaySlider)
        self.delayEdit = QtWidgets.QLineEdit(self.focusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delayEdit.sizePolicy().hasHeightForWidth())
        self.delayEdit.setSizePolicy(sizePolicy)
        self.delayEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.delayEdit.setObjectName("delayEdit")
        self.horizontalLayout_2.addWidget(self.delayEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startFocus = QtWidgets.QPushButton(self.focusGroup)
        self.startFocus.setMinimumSize(QtCore.QSize(135, 38))
        self.startFocus.setObjectName("startFocus")
        self.gridLayout_2.addWidget(self.startFocus, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 13, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.goalSlider = QtWidgets.QSlider(self.focusGroup)
        self.goalSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.goalSlider.setMaximum(1000)
        self.goalSlider.setSingleStep(10)
        self.goalSlider.setPageStep(100)
        self.goalSlider.setProperty("value", 800)
        self.goalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.goalSlider.setObjectName("goalSlider")
        self.horizontalLayout_3.addWidget(self.goalSlider)
        self.goalEdit = QtWidgets.QLineEdit(self.focusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goalEdit.sizePolicy().hasHeightForWidth())
        self.goalEdit.setSizePolicy(sizePolicy)
        self.goalEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.goalEdit.setObjectName("goalEdit")
        self.horizontalLayout_3.addWidget(self.goalEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 1, 1, 1)
        self.quantisizerLabel = QtWidgets.QLabel(self.focusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantisizerLabel.sizePolicy().hasHeightForWidth())
        self.quantisizerLabel.setSizePolicy(sizePolicy)
        self.quantisizerLabel.setObjectName("quantisizerLabel")
        self.gridLayout.addWidget(self.quantisizerLabel, 5, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quantSlider = QtWidgets.QSlider(self.focusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantSlider.sizePolicy().hasHeightForWidth())
        self.quantSlider.setSizePolicy(sizePolicy)
        self.quantSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.quantSlider.setMaximum(1000)
        self.quantSlider.setSingleStep(10)
        self.quantSlider.setPageStep(100)
        self.quantSlider.setProperty("value", 200)
        self.quantSlider.setOrientation(QtCore.Qt.Horizontal)
        self.quantSlider.setObjectName("quantSlider")
        self.horizontalLayout.addWidget(self.quantSlider)
        self.quantEdit = QtWidgets.QLineEdit(self.focusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantEdit.sizePolicy().hasHeightForWidth())
        self.quantEdit.setSizePolicy(sizePolicy)
        self.quantEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.quantEdit.setObjectName("quantEdit")
        self.horizontalLayout.addWidget(self.quantEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.goalLabel = QtWidgets.QLabel(self.focusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goalLabel.sizePolicy().hasHeightForWidth())
        self.goalLabel.setSizePolicy(sizePolicy)
        self.goalLabel.setObjectName("goalLabel")
        self.gridLayout.addWidget(self.goalLabel, 6, 1, 1, 1)
        self.delayLabel = QtWidgets.QLabel(self.focusGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delayLabel.sizePolicy().hasHeightForWidth())
        self.delayLabel.setSizePolicy(sizePolicy)
        self.delayLabel.setObjectName("delayLabel")
        self.gridLayout.addWidget(self.delayLabel, 8, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.focusGroup)

        self.retranslateUi(Autofocus)
        QtCore.QMetaObject.connectSlotsByName(Autofocus)

    def retranslateUi(self, Autofocus):
        _translate = QtCore.QCoreApplication.translate
        Autofocus.setWindowTitle(_translate("Autofocus", "Form"))
        self.focusGroup.setTitle(_translate("Autofocus", "Autofocus"))
        self.delayEdit.setText(_translate("Autofocus", "3"))
        self.startFocus.setText(_translate("Autofocus", "Start Autofocus"))
        self.goalEdit.setText(_translate("Autofocus", "0.8"))
        self.quantisizerLabel.setToolTip(_translate("Autofocus", "This specifies what input change counts as signal change"))
        self.quantisizerLabel.setText(_translate("Autofocus", "Quanisizer Treshold"))
        self.quantEdit.setText(_translate("Autofocus", "0.2"))
        self.goalLabel.setToolTip(_translate("Autofocus", "The goal specifies what signal strength counts as \"focus reached\" (in % of the best signal seen)"))
        self.goalLabel.setText(_translate("Autofocus", "Goal Treshold"))
        self.delayLabel.setToolTip(_translate("Autofocus", "After every move we wait for the given frames. This allows the camera image to catch up to the current position."))
        self.delayLabel.setText(_translate("Autofocus", "Delay Frames"))

